version: "3.5"

services:
  frontend:
    build:
      context: ./reactp
      dockerfile: ./Dockerfile
    image: "test/reactp"
    networks:
      my-network-name:
        aliases:
          - frontend
  backend:
    env_file: ".env"
    build:
      context: ./nodep
      dockerfile: ./Dockerfile
    image: "test/nodep"
    networks:
      my-network-name:
        aliases:
          - backend
  nginx-proxy:
    depends_on:
      - frontend
      - backend
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    image: "test/nginx"
    networks:
      my-network-name:
        aliases:
          - proxy-name
    ports:
      - 80:80
networks:
  my-network-name:
