version: "3.5"

services:
  frontend:
    build:
      context: ./reactp
      dockerfile: ./Dockerfile
    image: "img/reactp"
    networks:
      my-network-name:
        aliases:
          - frontend
  backend:
    # depends_on:
    #   - mysql-database
    env_file: ".env"
    build:
      context: ./nodep
      dockerfile: ./Dockerfile
    image: "img/nodep"
    networks:
      my-network-name:
        aliases:
          - backend
  nginx-proxy:
    depends_on:
      - frontend
      - backend
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    image: "img/nginx"
    networks:
      my-network-name:
        aliases:
          - proxy-name
    ports:
      - 80:80
  # mysql-database:
  #   image: mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: "root"
  #     MYSQL_ROOT_PASSWORD: "secret"
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     my-network-name:
  #       aliases:
  #         - mysql-name
networks:
  my-network-name:
