version: "3.5"

services:
  frontend:
    networks:
      my-network-name:
        aliases:
          - frontend-name
    build:
      context: ./reactp
      dockerfile: ./Dockerfile
    image: "mdu/reactp"
    ports:
      - "80:80"
  backend:
    networks:
      my-network-name:
        aliases:
          - backend-name
    env_file: ".env"
    build:
      context: ./nodep
      dockerfile: ./Dockerfile
    image: "mdu/nodep"
    ports:
      - "4000:4000"
  nginx-proxy:
    depends_on:
      - frontend
      - backend
    image: nginx:alpine
    volumes:
      - /nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      my-network-name:
        aliases:
          - proxy-name
    ports:
      - 1234:80
networks:
  my-network-name:
