version: "3.5"

services:
  frontend:
    networks:
      my-network-name:
        aliases:
          - mdu-react
    build:
      context: ./reactp
      dockerfile: ./Dockerfile
    image: "mdu/reactp"
  backend:
    env_file: ".env"
    build:
      context: ./nodep
      dockerfile: ./Dockerfile
    image: "mdu/nodep"
    networks:
      my-network-name:
        aliases:
          - mdu-backend
  nginx-proxy:
    depends_on:
      - frontend
      - backend
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    image: "mdu/nginx"
    networks:
      my-network-name:
        aliases:
          - proxy-name
    ports:
      - 80:80
networks:
  my-network-name:
