version: "3"

services:
  backend:
    env_file: ".env"
    build:
      context: ./nodep
      dockerfile: ./Dockerfile
    image: "mdu/nodep"
    ports:
      - "4000:4000"
  frontend:
    build:
      context: ./reactp
      dockerfile: ./Dockerfile
    image: "mdu/reactp"
    ports:
      - "80:80"
    links:
      - "backend:api"
